---
- name: install system pakcages and utils
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
     - ntp
     - openssl
     - git
     - git-core
     - awscli
     - golang
     - goaccess
     - htop
     - rsyslog
     - zip
     - vim
     - vim-common
     - curl
     - sysstat
     - figlet
     - multitail
     - python-pip
     - python3-pip
  tags:
    - packages
    - common

- name: correct python version selected
  alternatives:
    name: python
    path: /usr/bin/python3
    link: /usr/bin/python
  tags:
    - packages
    - packages-python
    - common
    - dpkg-reconf

- name: install pip packages ( aws .. )
  pip:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - awscli
      - pip
  tags:
    - awscli
    - common
    - packages

# @link http://bencane.com/2012/07/08/sar-sysstat-linux-performance-statistics-with-ease/
- name: enable /etc/default/sysstat
  lineinfile: >
    create=yes
    dest=/etc/default/sysstat
    regexp='^ENABLED='
    line='ENABLED="true"'
    state=present
  tags:
    - common-config
    - packages
    - common
