---
## Install Oh-my-zsh
- name: install git and zsh debian
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: 5400
  vars:
    packages:
     - git
     - zsh
     - zsh-antigen
  when: is_debian == True
  tags:
    - zsh-install
    - git

- name: install git and zsh redhat
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
     - git
     - zsh
  when: is_redhat == True
  tags:
    - zsh-install
    - git

- name: clone oh-my-zsh repo
  git:
    depth: 1
    repo: "{{ item.name }}"
    dest: "/usr/local/share/{{ item.dir }}"
  with_items:
    - name: https://github.com/robbyrussell/oh-my-zsh
      dir: oh-my-zsh
    - name: https://github.com/zsh-users/zsh-syntax-highlighting
      dir: zsh-syntax-highlighting
    - name: git://github.com/zsh-users/zsh-autosuggestions
      dir: zsh-autosuggestions
  tags:
    - zsh-install
    - zsh-config

- name: create conf folder in home directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - "/usr/local/share/oh-my-zsh/conf/"
    - "/usr/local/share/oh-my-zsh/cache/"
  tags:
    - zsh-config

- name: deploy .zshrc
  template:
    src: files/zshrc.in
    dest: /usr/local/share/oh-my-zsh/conf/zshrc
    mode: 0777
  tags:
    - zsh-config

- name: deploy .extra
  template:
    src: files/extra.in
    dest: "{{ home_dir | default('/home/') }}{{ user }}/.extra"
    mode: 0777
  tags:
    - zsh-config

- name: deploy .aliases
  template:
    src: files/aliases.in
    dest: "{{ home_dir | default('/home/') }}{{ user }}/.aliases"
    mode: 0777
  tags:
    - zsh-config

- name: deploy .bash_profile
  template:
    src: files/bash_profile.in
    dest: "{{ home_dir | default('/home/') }}{{ user }}/.bash_profile"
    mode: 0777
  tags:
    - zsh-config
    - bash_profile

- name: remove standard zshrc
  file:
    path: "{{ home_dir | default('/home/') }}{{ user }}/.zshrc"
    state: absent
  tags:
    - zsh-config

- name: symlink zshrc
  file:
    path: "{{ home_dir | default('/home/') }}{{ user }}/.zshrc"
    src: /usr/local/share/oh-my-zsh/conf/zshrc
    state: link
    mode: 0777
  tags:
    - zsh-symlink

- name: Update pamd rule's control in /etc/pam.d/chsh
  pamd:
    name: chsh
    type: auth
    control: required
    module_path: pam_shells.so
    new_control: optional
  tags:
    - zsh-pam

- name: set zsh as default shell
  shell: "chsh -s $(which zsh) {{ user }}"
  tags:
    - zsh-config
    - zsh-pam
